GuardianTalesWeb/Models/ErrorViewModel.cs
using System;

namespace GuardianTalesWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuardianTalesWeb/Models/GuardianTalesContext.cs
using Microsoft.EntityFrameworkCore;
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System.Linq;

namespace GuardianTalesWeb.Models
{
    public class GuardianTalesContext :DbContext
    {
        public DbSet<Joueur> Joueur { get; set; }
        public DbSet<Guilde> Guilde { get; set; }
        public DbSet<Team_Type> Team_Type { get; set; }
        public DbSet<Team> Team { get; set; }
        public string ConnectionString { get; set; }

        public GuardianTalesContext(string connectionString)
        {
            ConnectionString = connectionString;
        }

        public GuardianTalesContext()
        {
        }

        private MySqlConnection GetConnection()
        {
            return new MySqlConnection(ConnectionString);
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder )
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySQL("server=localhost;port=3306;user=root;password=;database=guardiantales");

            }
        }

        protected override void OnModelCreating(ModelBuilder model)
        {
            //Primary Keys
            model.Entity<Guilde>().HasKey(g => g.Guilde_Num).HasName("GUILD_NUM");
            model.Entity<Team_Type>().HasKey(tt => tt.Type_Team_Num).HasName("Type_Team_Num");
            model.Entity<Joueur>().HasKey(j => j.Joueur_Num).HasName("JOUEUR_NUM");
            model.Entity<Team>().HasKey(t => t.Type_Team_Num).HasName("Type_Team_Num");
            model.Entity<Team>().HasKey(t => t.Joueur_Num).HasName("Joueur_Num");
          
            //Association 1n entre joueur et guilde
            model.Entity<Joueur>().HasOne( j => j.Guilde).WithMany(g => g.Joueurs).HasForeignKey(j=> j.Guilde_Num).IsRequired();

          

            //Clé composée
            model.Entity<Team>()
           .HasKey(t => new { t.Type_Team_Num, t.Joueur_Num });

        }

        public List<Joueur> GetAllJoueur()//Retourne tous les joueurs
        {

            List<Joueur> retour = new List<Joueur>();
            using (var db = new GuardianTalesContext())
            {
                var joueurs = db.Joueur.Include(j => j.Guilde).ToList();
                foreach (Joueur joueur in joueurs)
                {
                    retour.Add(joueur);
                }

            }
            return retour;
        }
        public Joueur GetOneJoueur(int id)//Retourne le joueur d'id ID
        {
            using (var db = new GuardianTalesContext())
            {
                var joueur = db.Joueur.Where(j=>j.Joueur_Num == id).Include(joueur => joueur.Teams).ThenInclude(t => t.Team_Type).FirstOrDefault();
                if (joueur == null)
                {
                    throw new System.Exception();
                }
                else
                {
                    return joueur;
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id" id de la guilde></param>
        /// <returns>Liste des joueurs de la guilde</returns>
        public List<Joueur> GetJoueurFromGuild(int id)
        {
            using(var db = new GuardianTalesContext())
            {
                var joueurs = db.Joueur.Where(j => j.Guilde_Num == id).Include(j =>j.Guilde).Include(joueur => joueur.Teams).ThenInclude(t => t.Team_Type).ToList();
                return joueurs;
            }
        }
    }
}

GuardianTalesWeb/Models/Guilde.cs
using System.Collections.Generic;

namespace GuardianTalesWeb.Models
{
    public class Guilde
    {
       public int Guilde_Num { get; set; }

       public   string Guilde_Name { get; set; }

       public ICollection<Joueur> Joueurs { get; set; }

    }
}

GuardianTalesWeb/Models/Joueur.cs
using System.Collections.Generic;

namespace GuardianTalesWeb.Models
{
    public class Joueur
    {
        public int Joueur_Num { get; set; }
        public string Joueur_Nom { get; set;}
        public int Guilde_Num { get; set; }

        public Guilde Guilde { get; set; }
        public ICollection<Team> Teams { get; set; }
    }
}

GuardianTalesWeb/Models/Team.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace GuardianTalesWeb.Models
{
    public class Team
    {
        public int Type_Team_Num { get; set; }

        public int Joueur_Num { get; set; } 

        public int Team_Degats { get; set; }
        
        [ForeignKey("Type_Team_Num")]
        public Team_Type Team_Type { get; set; }
        
        [ForeignKey("Joueur_Num")]
        public Joueur Joueur { get; set; }
    }
}

GuardianTalesWeb/Models/Team_Type.cs
using System.Collections.Generic;

namespace GuardianTalesWeb.Models
{
    public class Team_Type
    {
        public int Type_Team_Num { get; set; }

        public string Type_Team_Lib { get; set; }

        public ICollection<Team> Teams { get; set; } //Toutes les teams d'un élément

    }
}

GuardianTalesWeb/Controllers/GuildeController.cs
using GuardianTalesWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace GuardianTalesWeb.Controllers
{
    public class GuildeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Guilde(int id)
        {
            GuardianTalesContext context = HttpContext.RequestServices.GetService(typeof(GuardianTalesWeb.Models.GuardianTalesContext)) as GuardianTalesContext;
            return View(context.GetJoueurFromGuild(id));
        }
    }
}

GuardianTalesWeb/Controllers/HomeController.cs
using GuardianTalesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GuardianTalesWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuardianTalesWeb/Controllers/JoueurController.cs
using GuardianTalesWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace GuardianTalesWeb.Controllers
{
    public class JoueurController : Controller
    {
        public IActionResult Index()
        {
            GuardianTalesContext context = HttpContext.RequestServices.GetService(typeof(GuardianTalesWeb.Models.GuardianTalesContext)) as GuardianTalesContext;
            return View(context.GetAllJoueur());
        }
        public IActionResult Joueur(int id)
        {
            GuardianTalesContext context = HttpContext.RequestServices.GetService(typeof(GuardianTalesWeb.Models.GuardianTalesContext)) as GuardianTalesContext;
            return View(context.GetOneJoueur(id));

        }
    }
}

GuardianTalesWeb/Views/Guilde/Guilde.cshtml
@model IEnumerable<GuardianTalesWeb.Models.Joueur>

@{
    ViewData["Title"] = "View";
}

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

GuardianTalesWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuardianTalesWeb/Views/Joueur/Index.cshtml
@model IEnumerable<GuardianTalesWeb.Models.Joueur>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Joueur_Num)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Joueur_Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guilde_Num)
            </th>

            <th>
                Nom Guilde
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Joueur_Num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Joueur_Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guilde_Num)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guilde.Guilde_Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Voir Teams", "Joueur", new { id=item.Joueur_Num  }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

GuardianTalesWeb/Views/Joueur/Joueur.cshtml
@model GuardianTalesWeb.Models.Joueur
@{
    ViewData["Title"] = "View";
}

<h1>Informations du joueur</h1>

<p> @Html.DisplayFor(model => model.Joueur_Nom)</p>

<h1>Teams du Joueur</h1>
<table class="table">
    <thead>
        <tr>
            <th>
               Element
            </th>
            <th>
                Dégats
            </th>
        </tr>
    </thead>





@foreach (var item in Model.Teams)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Team_Type.Type_Team_Lib)
        </td>
        <td>
            @Html.DisplayFor(modelItem=> item.Team_Degats)
        </td>
    </tr>
    
}
</table>

GuardianTalesWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuardianTalesWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuardianTalesWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GuardianTalesWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>